name: Create Release from Wheel

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release'
        required: true
        default: 'v1.0.0'

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-wheel.yaml
          name: cadquery-wheel
          path: wheels

      - name: List wheels
        run: |
          mkdir dist
          mv wheels/*.whl dist
          rm -rf wheels
          ls dist

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/cadquery-1.0.0-py3-none-any.whl"
          tag: ${{ github.event.inputs.tag_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}


